sudo: required

git:
  submodules: false
  
language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - pip install six
  - travis_wait 30 git submodule update --init --recursive

script:
  - python static/make_dockerfile.py
  - cd static/ && docker build -t ubuntu_10_04_build .
