name: Docker Image CI

on:
  push:
    branches: [ "integration" ]
  pull_request:
    branches: [ "integration" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - run: |
       cd dynamic
       docker build . --file Dockerfile --tag kdedow/ubuntu-10.04:$(date +%s)